# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SS

  target 'SS-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-haptic', :path => '../node_modules/react-native-haptic'

  end

  target 'SSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


